<?php
// This Release Apr-04-2011
//defined('XOOPS_ROOT_PATH') || exit('XOOPS root path not defined');
$moduleDirName    = basename(__DIR__);
$modinfo_lang = '_MI_' . strtoupper($moduleDirName);

$xoops = Xoops::getInstance();

$modversion                = array();
$modversion['name']        = AlumniLocale::MODULE_NAME;
$modversion['description'] = AlumniLocale::MODULE_DESC;
$modversion['version']     = '3.1';
$modversion['author']      = 'John Mordo';
$modversion['nickname']    = 'jlm69';
$modversion['credits']     = 'John Mordo';
$modversion['license']     = 'GNU GPL 2.0 or later';
$modversion['license_url'] = 'http://www.gnu.org/licenses/gpl-2.0.html';
$modversion['official']    = 0;
$modversion['help']        = 'page=help';
$modversion['image']       = 'images/alumni_slogo.png';
$modversion['dirname']     = $moduleDirName;

//$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
//$modversion['icons16']        = '../../Frameworks/moduleclasses/icons/16';
//$modversion['icons32']        = '../../Frameworks/moduleclasses/icons/32';

$modversion['release_date']        = '2015/06/01';
$modversion['module_website_url']  = 'http://www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['module_status']       = 'ALPHA 2';
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = '2.6.0';
$modversion['min_db']              = array('mysql' => '5.0.7', 'mysqli' => '5.0.7');

// paypal
$modversion['paypal']                  = array();
$modversion['paypal']['business']      = 'admin@jlmzone.com';
$modversion['paypal']['item_name']     = 'Donation : ' . AlumniLocale::MODULE_DESC;
$modversion['paypal']['amount']        = 0;
$modversion['paypal']['currency_code'] = 'USD';

$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';

// JQuery
$modversion['jquery'] = 1;

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['schema'] = 'sql/schema.yml';
//$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';


// Templates
//$modversion['templates'][1]['file'] = 'alumni_index.html';
//$modversion['templates'][1]['description'] = '';
//$modversion['templates'][2]['file'] = 'alumni_adlist.html';
//$modversion['templates'][2]['description'] = '';
//$modversion['templates'][3]['file'] = 'alumni_category.html';
//$modversion['templates'][3]['description'] = '';
//$modversion['templates'][4]['file'] = 'alumni_item.html';
//$modversion['templates'][4]['description'] = '';
//$modversion['templates'][5]['file'] = 'alumni_sendfriend.html';
//$modversion['templates'][5]['description'] = '';
//$modversion['templates'][6]['file'] = 'alumni_search.html';
//$modversion['templates'][6]['description'] = '';

// Tables created by sql file (without prefix!)
$modversion['tables'][1] = 'alumni_listing';
$modversion['tables'][2] = 'alumni_categories';
$modversion['tables'][3] = 'alumni_ip_log';

// Blocks
$modversion['blocks'][1]['file']        = 'alumni.php';
$modversion['blocks'][1]['name']        = $modinfo_lang . '_BNAME';
$modversion['blocks'][1]['description'] = $modinfo_lang . '_BNAME_DESC';
$modversion['blocks'][1]['show_func']   = 'alumni_show';
$modversion['blocks'][1]['edit_func']   = 'alumni_edit';
$modversion['blocks'][1]['template']    = 'alumni_block_new.html';
//$modversion['blocks'][1]['can_clone'] = 'true' ;
$modversion['blocks'][1]['options'] = 'date|10|25|0';

// Search
//$modversion['hasSearch'] = 1;
//$modversion['search']['file'] = 'include/search.inc.php';
//$modversion['search']['func'] = 'alumni_search';


// If you want the comments for ads instead of the seller uncomment below and comment out above and uncomment below.
// Comments
//$modversion['hasComments'] = 1;

//$modversion['comments']['itemName'] = 'lid';
//$modversion['comments']['pageName'] = 'viewad.php';
//$modversion['comments']['extraParams'] = array('lid');
// Comment callback functions - do not uncomment this line
//$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
//$modversion['comments']['callback']['approve'] = "".$moduleDirName."_com_approve";
//$modversion['comments']['callback']['update'] = "".$moduleDirName."_com_update";


// Config Settings
//$modversion['hasconfig'] = 1;
$i = 0;

$modversion['config'][$i]['name']        = 'alumni_usecat';
$modversion['config'][$i]['title']       = $modinfo_lang . '_USECAT';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_moderated']
++$i;
$modversion['config'][$i]['name']        = 'alumni_moderated';
$modversion['config'][$i]['title']       = $modinfo_lang . '_MODERAT';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '0';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_per_page']
++$i;
$modversion['config'][$i]['name']        = 'alumni_per_page';
$modversion['config'][$i]['title']       = $modinfo_lang . '_PERPAGE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '10';
$modversion['config'][$i]['options']     = array('10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40, '50' => 50);

// $xoopsModuleConfig['alumni_new_listing']
++$i;
$modversion['config'][$i]['name']        = 'alumni_new_listing';
$modversion['config'][$i]['title']       = $modinfo_lang . '_VIEWNEWCLASS';
$modversion['config'][$i]['description'] = $modinfo_lang . '_ONHOME';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_newalumni']
++$i;
$modversion['config'][$i]['name']        = 'alumni_newalumni';
$modversion['config'][$i]['title']       = $modinfo_lang . '_NUMNEW';
$modversion['config'][$i]['description'] = $modinfo_lang . '_ONHOME';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '10';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_countday']
++$i;
$modversion['config'][$i]['name']        = 'alumni_countday';
$modversion['config'][$i]['title']       = $modinfo_lang . '_NEWTIME';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INDAYS';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '3';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_photomax']
++$i;
$modversion['config'][$i]['name']        = 'alumni_photomax';
$modversion['config'][$i]['title']       = $modinfo_lang . '_MAXIIMGS';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INBYTES';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '500000';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_maxwide']
++$i;
$modversion['config'][$i]['name']        = 'alumni_maxwide';
$modversion['config'][$i]['title']       = $modinfo_lang . '_MAXWIDE';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INPIXEL';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '700';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_maxhigh']
++$i;
$modversion['config'][$i]['name']        = 'alumni_maxhigh';
$modversion['config'][$i]['title']       = $modinfo_lang . '_MAXHIGH';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INPIXEL';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1000';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_csortorder']
++$i;
$modversion['config'][$i]['name']        = 'alumni_csortorder';
$modversion['config'][$i]['title']       = $modinfo_lang . '_ORDER';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'title ASC';
$modversion['config'][$i]['options']     = array($modinfo_lang . '_ORDREALPHA' => 'title', $modinfo_lang . '_ORDREPERSO' => 'ordre');

// $xoopsModuleConfig['alumni_showsubcat']
++$i;
$modversion['config'][$i]['name']        = 'alumni_showsubcat';
$modversion['config'][$i]['title']       = $modinfo_lang . '_DISPLSUBCAT';
$modversion['config'][$i]['description'] = $modinfo_lang . '_ONHOME';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_numsubcat']
++$i;
$modversion['config'][$i]['name']        = 'alumni_numsubcat';
$modversion['config'][$i]['title']       = $modinfo_lang . '_NUMSUBCAT';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '4';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_csortorder']
++$i;
$modversion['config'][$i]['name']        = 'alumni_csortorder';
$modversion['config'][$i]['title']       = $modinfo_lang . '_ORDER';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'title';
$modversion['config'][$i]['options']     = array($modinfo_lang . '_ORDREALPHA' => 'title', $modinfo_lang . '_ORDREPERSO' => 'ordre');

// $xoopsModuleConfig['alumni_lsortorder']
++$i;
$modversion['config'][$i]['name']        = 'alumni_lsortorder';
$modversion['config'][$i]['title']       = $modinfo_lang . '_AORDER';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'name';
$modversion['config'][$i]['options']     = array($modinfo_lang . '_ORDER_DATE' => 'date DESC', $modinfo_lang . '_ORDER_NAME' => 'name ASC', $modinfo_lang . '_ORDER_POP' => 'hits DESC');

// $xoopsModuleConfig['alumni_form_options'] - Use WYSIWYG Editors?
++$i;
$editors                                 = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/class/xoopseditor');
$modversion['config'][$i]['name']        = 'alumni_form_options';
$modversion['config'][$i]['title']       = $modinfo_lang . '_EDITOR';
$modversion['config'][$i]['description'] = $modinfo_lang . '_LIST_EDITORS';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'dhtmltextarea';
$modversion['config'][$i]['options']     = $editors;

//$modversion['config'][$i]['name'] = 'alumni_form_options';
//$modversion['config'][$i]['title'] =  $modinfo_lang . '_EDITOR';
//$modversion['config'][$i]['description'] =  $modinfo_lang . '_LIST_EDITORS';
//$modversion['config'][$i]['formtype'] = 'select';
//$modversion['config'][$i]['valuetype'] = 'text';
//$modversion['config'][$i]['default'] = 'dhtmltextarea';
//XoopsLoad::load('XoopsEditorHandler');
//$editor_handler = XoopsEditorHandler::getInstance();
//$modversion['config'][$i]['options'] = array_flip($editor_handler->getList());


// $xoopsModuleConfig['alumni_use_captcha']
++$i;
$modversion['config'][$i]['name']        = 'alumni_use_captcha';
$modversion['config'][$i]['title']       = $modinfo_lang . '_USE_CAPTCHA';
$modversion['config'][$i]['description'] = $modinfo_lang . '_USE_CAPTCHA_DESC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_use_code']
++$i;
$modversion['config'][$i]['name']        = 'alumni_use_code';
$modversion['config'][$i]['title']       = $modinfo_lang . '_USE_INDEX_CODE';
$modversion['config'][$i]['description'] = $modinfo_lang . '_USE_INDEX_CODE_DESC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_use_banner']
++$i;
$modversion['config'][$i]['name']        = 'alumni_use_banner';
$modversion['config'][$i]['title']       = $modinfo_lang . '_USE_BANNER';
$modversion['config'][$i]['description'] = $modinfo_lang . '_USE_BANNER_DESC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

// $xoopsModuleConfig['alumni_index_code']
++$i;
$modversion['config'][$i]['name']        = 'alumni_index_code';
$modversion['config'][$i]['title']       = $modinfo_lang . '_INDEX_CODE';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INDEX_CODE_DESC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '';

// $xoopsModuleConfig['alumni_index_code_place']
++$i;
$modversion['config'][$i]['name']        = 'alumni_code_place';
$modversion['config'][$i]['title']       = $modinfo_lang . '_INDEX_CODE_PLACE';
$modversion['config'][$i]['description'] = $modinfo_lang . '_INDEX_CODE_PLACE_DESC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '5';

// $xoopsModuleConfig['alumni_offer_search'] - added for optional search
++$i;
$modversion['config'][$i]['name']        = 'alumni_offer_search';
$modversion['config'][$i]['title']       = $modinfo_lang . '_OFFER_SEARCH';
$modversion['config'][$i]['description'] = $modinfo_lang . '_OFFER_SEARCH_DESC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = '1';
$modversion['config'][$i]['options']     = array();

$modversion['notification']    = array();
$modversion['hasNotification'] = 1;
