tables:
    alumni_categories:
        options: {  }
        columns:
            cid:
                name: cid
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            pid:
                name: pid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: null
            title:
                name: title
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scaddress:
                name: scaddress
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scaddress2:
                name: scaddress2
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            sccity:
                name: sccity
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scstate:
                name: scstate
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            sczip:
                name: sczip
                type: string
                default: ''
                notnull: true
                length: 20
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scphone:
                name: scphone
                type: string
                default: ''
                notnull: true
                length: 30
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scfax:
                name: scfax
                type: string
                default: ''
                notnull: true
                length: 30
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scmotto:
                name: scmotto
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scurl:
                name: scurl
                type: string
                default: ''
                notnull: true
                length: 150
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            img:
                name: img
                type: string
                default: ''
                notnull: true
                length: 150
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            scphoto:
                name: scphoto
                type: string
                default: ''
                notnull: true
                length: 150
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            ordre:
                name: ordre
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [cid]
                unique: true
                primary: true
    alumni_ip_log:
        options: {  }
        columns:
            ip_id:
                name: ip_id
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            lid:
                name: lid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            date:
                name: date
                type: string
                default: null
                notnull: false
                length: 25
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            submitter:
                name: submitter
                type: string
                default: ''
                notnull: true
                length: 60
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            ipnumber:
                name: ipnumber
                type: string
                default: ''
                notnull: true
                length: 150
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            email:
                name: email
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [ip_id]
                unique: true
                primary: true
    alumni_listing:
        options: {  }
        columns:
            lid:
                name: lid
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            cid:
                name: cid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            name:
                name: name
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            mname:
                name: mname
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            lname:
                name: lname
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            school:
                name: school
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            year:
                name: year
                type: string
                default: ''
                notnull: true
                length: 4
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            studies:
                name: studies
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            activities:
                name: activities
                type: text
                default: null
                notnull: true
                length: 16777215
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            extrainfo:
                name: extrainfo
                type: text
                default: null
                notnull: true
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            occ:
                name: occ
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            date:
                name: date
                type: string
                default: null
                notnull: false
                length: 25
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            email:
                name: email
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            submitter:
                name: submitter
                type: string
                default: ''
                notnull: true
                length: 60
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            usid:
                name: usid
                type: string
                default: ''
                notnull: true
                length: 6
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            town:
                name: town
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            valid:
                name: valid
                type: string
                default: ''
                notnull: true
                length: 11
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            photo:
                name: photo
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            photo2:
                name: photo2
                type: string
                default: ''
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
            view:
                name: view
                type: string
                default: '0'
                notnull: true
                length: 10
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: latin1_swedish_ci
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [lid]
                unique: true
                primary: true
